[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[rules.allowlist]
description = "Global allowlist patterns"
paths = [
    '''.*\.example$'''
]