[project]
name = "purchase-request-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.6",
    "python-dotenv>=1.0.0",
    "ruff>=0.12.4",
    "openpyxl>=3.1.0",
    "pillow>=11.3.0",
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "google-api-python-client>=2.0.0",
    "google-auth>=2.0.0",
    "google-auth-oauthlib>=1.0.0",
    "google-auth-httplib2>=0.2.0",
    "itsdangerous>=2.2.0",
    "sqlalchemy>=2.0.41",
]
